### PR TITLE
Feat: Load more links.

### PR DESCRIPTION
**Pull request by 4silvertooth**
The posts are now loaded in parallel with `promise.when`, the comment loading needs to change as it's forced to load only 10 or less comments.

### CODE REVIEW

**Comment by GirkovArpa** [comment]
Thanks, I will remove the limits.  Also I didn't know TIScript supported spread syntax:
```javascript
...ids.map(:url: fetch("item/" + url))
```

**Comment by GirkovArpa** [comment]
Very nice functionality 👍

**Comment by 4silvertooth** [comment]
I've purposely used some of the functionality, just for the sake of learning.

**Comment by GirkovArpa** [comment]
Same!

**Pull request merged**
